    <table class="table table-striped">
        <tbody>
            <tr>
                <td><strong><?=lang('Site.invoice_id')?></strong></td>
                <td><?=$invoice['reference']?></td>
            </tr>
            <tr>
                <td><strong><?=lang('Site.total_price')?></strong></td>
                <td><?=formatMoney($invoice['total_price'])?></td>
            </tr>
            <tr>
                <td><strong><?=lang('Site.tax')?></strong></td>
                <td><?=formatMoney($invoice['tax'])?></td>
            </tr>
            <tr>
                <td><strong><?=lang('Site.total_due')?></strong></td>
                <td><?=formatMoney($invoice['total_due'])?></td>
            </tr>
            <tr>
                <td></td>
                <td></td>
            </tr>
        </tbody>
    </table>
<br>
<br>
<br>
    <table class="table table-striped">
        <thead>
            <tr>
                <th><?=lang('Site.name')?></th>
                <th><?=lang('Site.quantity')?></th>
                <th><?=lang('Site.unit_price')?></th>
                <th><?=lang('Site.total_price')?></th>
            </tr>
        </thead>
        <tbody>
<?php
    $items = json_decode($invoice['items'], true);

    if(!empty($items['items']))
    {
        foreach($items['items'] as $item)
        {
?>
            <tr>
                <td><?=$item['name']?></td>
                <td><?=$item['quantity']?></td>
                <td><?=formatMoney($item['unit_price'])?></td>
                <td><?=formatMoney($item['total_price'])?></td>
            </tr>
<?php
        }
    }
    if(!empty($items['subscription']))
    {
?>
            <tr>
                <td><?=$items['subscription']['name']?></td>
                <td><?=$items['subscription']['duration']?></td>
                <td><?=formatMoney($items['subscription']['unit_price'])?></td>
                <td><?=formatMoney($items['subscription']['total_price'])?></td>
            </tr>
<?php
    }
    if(!empty($items['shipping']))
    {
?>
                        <tr>
                            <td><?=$items['shipping']['item_name']?></td>
                            <td>1</td>
                            <td><?=formatMoney($items['shipping']['shipping_fee'])?></td>
                            <td><?=formatMoney($items['shipping']['shipping_fee'])?></td>
                        </tr>
<?php
    }
    if(!empty($items['custom_items']))
    {
        foreach($items['custom_items'] as $custom_item){
?>
                        <tr>
                            <td>
                                <?=$custom_item['name']?>
                            </td>
                            <td>1</td>
                            <td><?=formatMoney($custom_item['price'])?></td>
                            <td><?=formatMoney($custom_item['price'])?></td>
                        </tr>
<?php
        }
    }
?>
        </tbody>
    </table>