<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class AppSettingsSeed extends Seeder
{
	public function run()
	{
        $data = [
                    [
                        'key'           => 'admin_theme',
                        'value'         => 'AdminLTE',
                        'group'         => 'appearance',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'admin_theme_navbar_background_color',
                        'value'         => 'gray-dark',
                        'group'         => 'appearance',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'admin_theme_navbar_text_color',
                        'value'         => 'dark',
                        'group'         => 'appearance',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'admin_theme_sidebar_background_color',
                        'value'         => 'dark',
                        'group'         => 'appearance',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'admin_theme_sidebar_highlight_color',
                        'value'         => 'lime',
                        'group'         => 'appearance',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'admin_theme_accent_color',
                        'value'         => 'primary',
                        'group'         => 'appearance',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'user_theme',
                        'value'         => 'AdminLTE',
                        'group'         => 'appearance',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'user_theme_navbar_background_color',
                        'value'         => 'lightblue',
                        'group'         => 'appearance',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'user_theme_navbar_text_color',
                        'value'         => 'dark',
                        'group'         => 'appearance',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'user_theme_sidebar_background_color',
                        'value'         => 'dark',
                        'group'         => 'appearance',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'user_theme_sidebar_highlight_color',
                        'value'         => 'lightblue',
                        'group'         => 'appearance',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'user_theme_accent_color',
                        'value'         => 'primary',
                        'group'         => 'appearance',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'front_theme',
                        'value'         => 'LandingPage1',
                        'group'         => 'appearance',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'auth_theme',
                        'value'         => 'AdminLTE',
                        'group'         => 'appearance',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'site_name',
                        'value'         => 'Laundromart',
                        'group'         => 'site',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'site_title',
                        'value'         => 'Welcome to Laundromart',
                        'group'         => 'site',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'support_email',
                        'value'         => '',
                        'group'         => 'site',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'logo',
                        'value'         => 'logo.png',
                        'group'         => 'site',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'currency',
                        'value'         => '$',
                        'group'         => 'site',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'tax_type',
                        'value'         => 'percentage',
                        'group'         => 'site',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'tax_amount',
                        'value'         => '0',
                        'group'         => 'site',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'timezone',
                        'value'         => 'Africa/Lagos',
                        'group'         => 'site',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'date_format',
                        'value'         => 'd M, Y',
                        'group'         => 'site',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'time_format',
                        'value'         => 'h:i a',
                        'group'         => 'site',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'datetime_format',
                        'value'         => 'd M, Y h:i a',
                        'group'         => 'site',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'upload_path',
                        'value'         => 'public/uploads',
                        'group'         => 'site',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'default_language',
                        'value'         => 'en',
                        'group'         => 'site',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'seo_homepage_title',
                        'value'         => 'Laundromart',
                        'group'         => 'seo',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'seo_homepage_keywords',
                        'value'         => 'Laundry,Dry-Clean,Clean,Iron,Wash',
                        'group'         => 'seo',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'seo_homepage_description',
                        'value'         => 'Welcome to Laundromart',
                        'group'         => 'seo',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'seo_product_page_title',
                        'value'         => 'Laundromart - Products',
                        'group'         => 'seo',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'seo_product_page_keywords',
                        'value'         => 'Products,Service,Shirt,Pants,Shoe',
                        'group'         => 'seo',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'seo_product_page_description',
                        'value'         => 'Products Page Laundromart',
                        'group'         => 'seo',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'seo_plan_page_title',
                        'value'         => 'Laundromart - Subscription Plans',
                        'group'         => 'seo',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'seo_plan_page_keywords',
                        'value'         => 'Subscription,Plans,Subscribe',
                        'group'         => 'seo',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'seo_plan_page_description',
                        'value'         => 'Laundromart - Subscription Plans',
                        'group'         => 'seo',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'seo_contact_page_title',
                        'value'         => 'Laundromart - Contact Us',
                        'group'         => 'seo',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'seo_contact_page_keywords',
                        'value'         => 'Contact Us',
                        'group'         => 'seo',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'seo_contact_page_description',
                        'value'         => 'Laundromart - Contact Us',
                        'group'         => 'seo',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'seo_cart_page_title',
                        'value'         => 'Laundromart - Shopping Cart',
                        'group'         => 'seo',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'seo_cart_page_keywords',
                        'value'         => 'Shopping Cart,Checkout,Order',
                        'group'         => 'seo',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'seo_cart_page_description',
                        'value'         => 'Laundromart - Checkout',
                        'group'         => 'seo',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'seo_login_page_title',
                        'value'         => 'Laundromart - Login',
                        'group'         => 'seo',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'seo_login_page_keywords',
                        'value'         => 'login',
                        'group'         => 'seo',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'seo_login_page_description',
                        'value'         => 'Laundromart - Login to Your Account',
                        'group'         => 'seo',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'seo_register_page_title',
                        'value'         => 'Laundromart - Register',
                        'group'         => 'seo',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'seo_register_page_keywords',
                        'value'         => 'Register,Create Account',
                        'group'         => 'seo',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'seo_register_page_description',
                        'value'         => 'Laundromart - Register',
                        'group'         => 'seo',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'seo_branch_locator_page_title',
                        'value'         => 'Laundromart - Find Us',
                        'group'         => 'seo',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'seo_branch_locator_page_keywords',
                        'value'         => 'Address,Find Us,Our Branches',
                        'group'         => 'seo',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'seo_branch_locator_page_description',
                        'value'         => 'Laundromart - Find Us',
                        'group'         => 'seo',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'sender_email',
                        'value'         => '',
                        'group'         => 'mail',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'sender_name',
                        'value'         => '',
                        'group'         => 'mail',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'mail_protocol',
                        'value'         => 'sendmail',
                        'group'         => 'mail',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'mail_template',
                        'value'         => 'Ohmysmtp',
                        'group'         => 'mail',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'mail_charset',
                        'value'         => 'utf-8',
                        'group'         => 'mail',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'smtp_host',
                        'value'         => '',
                        'group'         => 'mail',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'smtp_user',
                        'value'         => '',
                        'group'         => 'mail',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'smtp_pass',
                        'value'         => '',
                        'group'         => 'mail',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'smtp_port',
                        'value'         => '',
                        'group'         => 'mail',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'smtp_timeout',
                        'value'         => 5,
                        'group'         => 'mail',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'smtp_keep_alive',
                        'value'         => "no",
                        'group'         => 'mail',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'smtp_encryption',
                        'value'         => 'tls',
                        'group'         => 'mail',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'sendmail_path',
                        'value'         => '/usr/sbin/sendmail',
                        'group'         => 'mail',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'mail_footer',
                        'value'         => '',
                        'group'         => 'mail',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'enable_welcome_mail',
                        'value'         => "yes",
                        'group'         => 'mail',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'welcome_mail_message',
                        'value'         => 'Hi {{FIRSTNAME}} {{LASTNAME}}, welcome to our website.',
                        'group'         => 'mail',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'welcome_mail_subject',
                        'value'         => 'Welcome to our website',
                        'group'         => 'mail',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'enable_reset_password_mail',
                        'value'         => "yes",
                        'group'         => 'mail',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'reset_password_mail_message',
                        'value'         => 'Hi {{USERNAME}}, click the button below to reset your account password.<br>{{RESET PASSWORD BUTTON}}<br>or copy and paste this link in your browser {{RESET PASSWORD LINK}}',
                        'group'         => 'mail',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'reset_password_mail_subject',
                        'value'         => 'Reset Password',
                        'group'         => 'mail',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'enable_verify_account_mail',
                        'value'         => "yes",
                        'group'         => 'mail',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'verify_account_mail_message',
                        'value'         => 'Hi {{LASTNAME}} {{FIRSTNAME}}, click the button below to verify your account.<br>{{VERIFY EMAIL BUTTON}}<br>or copy and paste the link below in your browser <br> {{VERIFY EMAIL LINK}}',
                        'group'         => 'mail',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'verify_account_mail_subject',
                        'value'         => 'Verify Email Address',
                        'group'         => 'mail',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'enable_order_confirmed_mail',
                        'value'         => "yes",
                        'group'         => 'mail',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'order_confirmed_mail_message',
                        'value'         => '<h2 style="font-family: " source="" sans="" pro",="" -apple-system,="" blinkmacsystemfont,="" "segoe="" ui",="" roboto,="" "helvetica="" neue",="" arial,="" sans-serif,="" "apple="" color="" emoji",="" ui="" symbol";="" color:="" rgb(0,="" 0,="" 0);"=""><span style="font-weight: bolder;">Order Confirmed</span></h2><p>Hi {{FIRSTNAME}}<span style="font-size: 1rem;">&nbsp;</span><span style="font-size: 1rem;">{{</span><span style="font-size: 1rem; background-color: rgb(244, 246, 249); color: rgb(33, 37, 41);">LASTNAME</span><span style="font-size: 1rem;">}}</span><span style="font-size: 1rem;">, your order have been confirmed. Your order status is {{ORDER STATUS}}</span></p><p><font color="#212529"><span style="background-color: rgb(244, 246, 249);">Attached is a breakdown of your order:</span></font></p><p><span style="background-color: rgb(244, 246, 249); color: rgb(33, 37, 41); font-size: 1rem;">{{ORDER TABLE}}</span></p>',
                        'group'         => 'mail',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'order_confirmed_mail_subject',
                        'value'         => 'Order Successful',
                        'group'         => 'mail',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'enable_subscription_confirmed_mail',
                        'value'         => "yes",
                        'group'         => 'mail',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'subscription_confirmed_mail_message',
                        'value'         => '<h2 style="font-family: " source="" sans="" pro",="" -apple-system,="" blinkmacsystemfont,="" "segoe="" ui",="" roboto,="" "helvetica="" neue",="" arial,="" sans-serif,="" "apple="" color="" emoji",="" ui="" symbol";="" color:="" rgb(0,="" 0,="" 0);"=""><span style="font-weight: bolder;">Subscription Confirmed</span></h2><p>Hi {{FIRSTNAME}}<span style="font-size: 1rem;">&nbsp;</span><span style="font-size: 1rem;">{{</span><span style="font-size: 1rem; background-color: rgb(244, 246, 249); color: rgb(33, 37, 41);">LASTNAME</span><span style="font-size: 1rem;">}}</span><span style="font-size: 1rem;">, your subscription have been confirmed. Your subscription status is {{SUBSCRIPTION STATUS}}</span></p><p><font color="#212529"><span style="background-color: rgb(244, 246, 249);">Attached is a breakdown of your subscription:</span></font></p><p><span style="background-color: rgb(244, 246, 249); color: rgb(33, 37, 41); font-size: 1rem;">{{SUBSCRIPTION TABLE}}</span></p>',
                        'group'         => 'mail',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'subscription_confirmed_mail_subject',
                        'value'         => 'Subscription Successful',
                        'group'         => 'mail',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'enable_pickup_scheduled_mail',
                        'value'         => "yes",
                        'group'         => 'mail',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'pickup_scheduled_mail_message',
                        'value'         => '<h2 style="font-family: " source="" sans="" pro",="" -apple-system,="" blinkmacsystemfont,="" "segoe="" ui",="" roboto,="" "helvetica="" neue",="" arial,="" sans-serif,="" "apple="" color="" emoji",="" ui="" symbol";="" color:="" rgb(0,="" 0,="" 0);"=""><b>Scheduled Pickup</b></h2><p>Hi {{FIRSTNAME}}<span style="font-size: 1rem;">&nbsp;</span><span style="font-size: 1rem;">{{</span><span style="font-size: 1rem; background-color: rgb(244, 246, 249); color: rgb(33, 37, 41);">LASTNAME</span><span style="font-size: 1rem;">}}</span><span style="font-size: 1rem;">, A pickup has been scheduled for {{PICKUP TIME}}</span></p>',
                        'group'         => 'mail',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'pickup_scheduled_mail_subject',
                        'value'         => 'Pickup Scheduled',
                        'group'         => 'mail',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'enable_pickup_schedule_reminder_mail',
                        'value'         => "no",
                        'group'         => 'mail',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'pickup_schedule_reminder_mail_message',
                        'value'         => '<h2 style="font-family: " source="" sans="" pro",="" -apple-system,="" blinkmacsystemfont,="" "segoe="" ui",="" roboto,="" "helvetica="" neue",="" arial,="" sans-serif,="" "apple="" color="" emoji",="" ui="" symbol";="" color:="" rgb(0,="" 0,="" 0);"=""><span style="font-weight: bolder;">Upcoming Pickup</span></h2><p>Hi {{FIRSTNAME}}<span style="font-size: 1rem;">&nbsp;</span><span style="font-size: 1rem;">{{</span><span style="font-size: 1rem; background-color: rgb(244, 246, 249); color: rgb(33, 37, 41);">LASTNAME</span><span style="font-size: 1rem;">}}</span><span style="font-size: 1rem;">, This is to remind you of your scheduled pickup, which comes up in {{TIME LEFT}} time.</span></p>',
                        'group'         => 'mail',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'pickup_schedule_reminder_mail_subject',
                        'value'         => 'Pickup Reminder',
                        'group'         => 'mail',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'enable_pickup_successful_mail',
                        'value'         => "no",
                        'group'         => 'mail',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'pickup_successful_mail_message',
                        'value'         => '<h2><b>Pickup Successful</b></h2><p>Hi {{FIRSTNAME}}<span style="font-size: 1rem;">&nbsp;</span><span style="font-size: 1rem;">{{</span><span style="font-size: 1rem; background-color: rgb(244, 246, 249); color: rgb(33, 37, 41);">LASTNAME</span><span style="font-size: 1rem;">}}</span><span style="font-size: 1rem;">, Your scheduled pickup has been completed</span><span style="font-size: 1rem;">.</span><b><br></b></p>',
                        'group'         => 'mail',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'pickup_successful_mail_subject',
                        'value'         => 'Pickup Successful',
                        'group'         => 'mail',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'enable_pickup_failed_mail',
                        'value'         => "no",
                        'group'         => 'mail',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'pickup_failed_mail_message',
                        'value'         => '<h2><b>Pickup Failed</b></h2><p>Hi {{FIRSTNAME}}<span style="font-size: 1rem;">&nbsp;</span><span style="font-size: 1rem;">{{</span><span style="font-size: 1rem; background-color: rgb(244, 246, 249); color: rgb(33, 37, 41);">LASTNAME</span><span style="font-size: 1rem;">}}</span><span style="font-size: 1rem;">, Attempted pickup of your Laundry has failed</span><span style="font-size: 1rem;">.</span><b><br></b></p>',
                        'group'         => 'mail',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'pickup_failed_mail_subject',
                        'value'         => 'Pickup Failed',
                        'group'         => 'mail',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'enable_delivery_scheduled_mail',
                        'value'         => "yes",
                        'group'         => 'mail',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'delivery_scheduled_mail_message',
                        'value'         => '<h2 style="font-family: " source="" sans="" pro",="" -apple-system,="" blinkmacsystemfont,="" "segoe="" ui",="" roboto,="" "helvetica="" neue",="" arial,="" sans-serif,="" "apple="" color="" emoji",="" ui="" symbol";="" color:="" rgb(0,="" 0,="" 0);"=""><b>Scheduled Delivery</b></h2><p>Hi {{FIRSTNAME}}<span style="font-size: 1rem;">&nbsp;</span><span style="font-size: 1rem;">{{</span><span style="font-size: 1rem; background-color: rgb(244, 246, 249); color: rgb(33, 37, 41);">LASTNAME</span><span style="font-size: 1rem;">}}</span><span style="font-size: 1rem;">, A delivery has been scheduled for {{DELIVERY TIME}}</span></p>',
                        'group'         => 'mail',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'delivery_scheduled_mail_subject',
                        'value'         => 'Delivery Scheduled',
                        'group'         => 'mail',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'enable_delivery_schedule_reminder_mail',
                        'value'         => "no",
                        'group'         => 'mail',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'delivery_schedule_reminder_mail_message',
                        'value'         => '<h2 style="font-family: " source="" sans="" pro",="" -apple-system,="" blinkmacsystemfont,="" "segoe="" ui",="" roboto,="" "helvetica="" neue",="" arial,="" sans-serif,="" "apple="" color="" emoji",="" ui="" symbol";="" color:="" rgb(0,="" 0,="" 0);"=""><span style="font-weight: bolder;">Upcoming Delivery</span></h2><p>Hi {{FIRSTNAME}}<span style="font-size: 1rem;">&nbsp;</span><span style="font-size: 1rem;">{{</span><span style="font-size: 1rem; background-color: rgb(244, 246, 249); color: rgb(33, 37, 41);">LASTNAME</span><span style="font-size: 1rem;">}}</span><span style="font-size: 1rem;">, This is to remind you of your sc</span>he<span style="font-size: 1rem;">duled delivery, which comes up in {{TIME LEFT}} time.</span></p>',
                        'group'         => 'mail',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'delivery_schedule_reminder_mail_subject',
                        'value'         => 'Upcoming Delivery',
                        'group'         => 'mail',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'enable_delivery_successful_mail',
                        'value'         => "no",
                        'group'         => 'mail',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'delivery_successful_mail_message',
                        'value'         => '<h2><b>Delivery Successful</b></h2><p>Hi {{FIRSTNAME}}<span style="font-size: 1rem;">&nbsp;</span><span style="font-size: 1rem;">{{</span><span style="font-size: 1rem; background-color: rgb(244, 246, 249); color: rgb(33, 37, 41);">LASTNAME</span><span style="font-size: 1rem;">}}</span><span style="font-size: 1rem;">, Your scheduled delivery has been completed</span><span style="font-size: 1rem;">.</span><b><br></b></p>',
                        'group'         => 'mail',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'delivery_successful_mail_subject',
                        'value'         => 'Delivery Successful',
                        'group'         => 'mail',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'enable_delivery_failed_mail',
                        'value'         => "no",
                        'group'         => 'mail',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'delivery_failed_mail_message',
                        'value'         => '<h2><b>Delivery Failed</b></h2><p>Hi {{FIRSTNAME}}<span style="font-size: 1rem;">&nbsp;</span><span style="font-size: 1rem;">{{</span><span style="font-size: 1rem; background-color: rgb(244, 246, 249); color: rgb(33, 37, 41);">LASTNAME</span><span style="font-size: 1rem;">}}</span><span style="font-size: 1rem;">, A scheduled laundry delivery has failed</span><span style="font-size: 1rem;">.</span><b><br></b></p>',
                        'group'         => 'mail',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'delivery_failed_mail_subject',
                        'value'         => 'Delivery Failed',
                        'group'         => 'mail',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'enable_invoice_created_mail',
                        'value'         => "yes",
                        'group'         => 'mail',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'invoice_created_mail_message',
                        'value'         => '<h2><b>Invoice Created</b></h2><p><span style="font-size: 1rem;">Hi {{FIRSTNAME}}</span><span style="font-size: 1rem;">&nbsp;</span><span style="font-size: 1rem;">{{</span><span style="font-size: 1rem; background-color: rgb(244, 246, 249); color: rgb(33, 37, 41);">LASTNAME</span><span style="font-size: 1rem;">}}</span><span style="font-size: 1rem;">,&nbsp;</span><span style="font-size: 1rem;">A new Invoice has been created for you. Attached is the summary.</span><br></p><p>{{UNPAID INVOICE TABLE}}</p><p>{{VIEW INVOICE DETAILS BUTTON}}</p><p>{{PAY INVOICE BUTTON}}</p>',
                        'group'         => 'mail',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'invoice_created_mail_subject',
                        'value'         => 'Invoice Created',
                        'group'         => 'mail',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'enable_invoice_paid_mail',
                        'value'         => "yes",
                        'group'         => 'mail',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'invoice_paid_mail_message',
                        'value'         => '<h2><b>Invoice Paid</b></h2><p><span style="font-size: 1rem;">Hi {{FIRSTNAME}}</span><span style="font-size: 1rem;">&nbsp;</span><span style="font-size: 1rem;">{{</span><span style="font-size: 1rem; background-color: rgb(244, 246, 249); color: rgb(33, 37, 41);">LASTNAME</span><span style="font-size: 1rem;">}}</span><span style="font-size: 1rem;">,&nbsp;</span>Your Invoice {{INVOICE ID}} has been paid. Attached is your payment summary.</p><p>{{PAID INVOICE TABLE}}</p><p>{{VIEW INVOICE DETAILS BUTTON}}<br></p>',
                        'group'         => 'mail',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'invoice_paid_mail_subject',
                        'value'         => 'Invoice Paid',
                        'group'         => 'mail',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'enable_products_feature',
                        'value'         => "yes",
                        'group'         => 'feature',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'enable_subscription_feature',
                        'value'         => "yes",
                        'group'         => 'feature',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'open_hours_monday_from',
                        'value'         => '08:00',
                        'group'         => 'working_hours',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'open_hours_monday_to',
                        'value'         => '16:00',
                        'group'         => 'working_hours',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'open_hours_tuesday_from',
                        'value'         => '08:00',
                        'group'         => 'working_hours',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'open_hours_tuesday_to',
                        'value'         => '16:00',
                        'group'         => 'working_hours',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'open_hours_wednesday_from',
                        'value'         => '08:00',
                        'group'         => 'working_hours',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'open_hours_wednesday_to',
                        'value'         => '16:00',
                        'group'         => 'working_hours',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'open_hours_thursday_from',
                        'value'         => '08:00',
                        'group'         => 'working_hours',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'open_hours_thursday_to',
                        'value'         => '16:00',
                        'group'         => 'working_hours',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'open_hours_friday_from',
                        'value'         => '08:00',
                        'group'         => 'working_hours',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'open_hours_friday_to',
                        'value'         => '16:00',
                        'group'         => 'working_hours',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'open_hours_saturday_from',
                        'value'         => '10:00',
                        'group'         => 'working_hours',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'open_hours_saturday_to',
                        'value'         => '14:00',
                        'group'         => 'working_hours',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'open_hours_sunday_from',
                        'value'         => '',
                        'group'         => 'working_hours',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'open_hours_sunday_to',
                        'value'         => '',
                        'group'         => 'working_hours',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'pickup_hours_monday_from',
                        'value'         => '08:00',
                        'group'         => 'working_hours',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'pickup_hours_monday_to',
                        'value'         => '14:00',
                        'group'         => 'working_hours',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'pickup_hours_tuesday_from',
                        'value'         => '08:00',
                        'group'         => 'working_hours',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'pickup_hours_tuesday_to',
                        'value'         => '14:00',
                        'group'         => 'working_hours',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'pickup_hours_wednesday_from',
                        'value'         => '08:00',
                        'group'         => 'working_hours',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'pickup_hours_wednesday_to',
                        'value'         => '14:00',
                        'group'         => 'working_hours',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'pickup_hours_thursday_from',
                        'value'         => '08:00',
                        'group'         => 'working_hours',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'pickup_hours_thursday_to',
                        'value'         => '14:00',
                        'group'         => 'working_hours',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'pickup_hours_friday_from',
                        'value'         => '08:00',
                        'group'         => 'working_hours',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'pickup_hours_friday_to',
                        'value'         => '13:00',
                        'group'         => 'working_hours',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'pickup_hours_saturday_from',
                        'value'         => '',
                        'group'         => 'working_hours',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'pickup_hours_saturday_to',
                        'value'         => '',
                        'group'         => 'working_hours',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'pickup_hours_sunday_from',
                        'value'         => '',
                        'group'         => 'working_hours',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'pickup_hours_sunday_to',
                        'value'         => '',
                        'group'         => 'working_hours',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'delivery_hours_monday_from',
                        'value'         => '08:00',
                        'group'         => 'working_hours',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'delivery_hours_monday_to',
                        'value'         => '14:00',
                        'group'         => 'working_hours',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'delivery_hours_tuesday_from',
                        'value'         => '08:00',
                        'group'         => 'working_hours',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'delivery_hours_tuesday_to',
                        'value'         => '14:00',
                        'group'         => 'working_hours',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'delivery_hours_wednesday_from',
                        'value'         => '08:00',
                        'group'         => 'working_hours',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'delivery_hours_wednesday_to',
                        'value'         => '14:00',
                        'group'         => 'working_hours',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'delivery_hours_thursday_from',
                        'value'         => '08:00',
                        'group'         => 'working_hours',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'delivery_hours_thursday_to',
                        'value'         => '14:00',
                        'group'         => 'working_hours',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'delivery_hours_friday_from',
                        'value'         => '08:00',
                        'group'         => 'working_hours',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'delivery_hours_friday_to',
                        'value'         => '14:00',
                        'group'         => 'working_hours',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'delivery_hours_saturday_from',
                        'value'         => '',
                        'group'         => 'working_hours',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'delivery_hours_saturday_to',
                        'value'         => '',
                        'group'         => 'working_hours',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'delivery_hours_sunday_from',
                        'value'         => '',
                        'group'         => 'working_hours',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'delivery_hours_sunday_to',
                        'value'         => '',
                        'group'         => 'working_hours',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'enable_products_page',
                        'value'         => "yes",
                        'group'         => 'page',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'enable_subscription_plans_page',
                        'value'         => "yes",
                        'group'         => 'page',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'enable_contact_us_page',
                        'value'         => "yes",
                        'group'         => 'page',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'enable_branch_locator_page',
                        'value'         => "yes",
                        'group'         => 'page',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'footer_text',
                        'value'         => 'Copyright &copy; 2022. All rights reserved.',
                        'group'         => 'page',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'register_page_terms_text',
                        'value'         => '<span style="color: rgb(102, 102, 102); font-weight: 700;">I agree to the&nbsp;</span><a href="http://localhost/personal/laundromart/terms-conditions" style="background-color: rgb(255, 255, 255); font-weight: 700;" target="_blank">terms</a>',
                        'group'         => 'page',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'default_payment_gateway',
                        'value'         => "paypal",
                        'group'         => 'payment_gateway',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'enable_stripe_payment_gateway',
                        'value'         => "yes",
                        'group'         => 'payment_gateway',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                    [
                        'key'           => 'stripe_payment_gateway_currency',
                        'value'         => "USD",
                        'group'         => 'payment_gateway',
                        'created_at'    => date("Y-m-d H:i:s"),
                    ],
                ];

        foreach($data as $d)
        {
            $this->db->table('app_settings')->insert($d);
        }
	}
}
